name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1" # Runs every Monday at 13:00 UTC
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Best Practice: Use the latest version
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/BankCx/WireTransfer.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: main
          # Branch to merge into downstream
          downstream_branch: main
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}
